name: eggstra_farms_ltd
description: "Eggstra Farms Ltd - Premium Agricultural Products Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.11
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_analytics: ^10.10.7
  firebase_crashlytics: ^3.5.7
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^14.2.7
  
  # HTTP & Networking
  http: ^1.2.2
  dio: ^5.4.3+1
  
  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.3
  
  # Image Handling
  image_picker: ^1.1.2
  image_cropper: ^8.0.1
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.4.2
  crypto: ^3.0.3
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.2
  
  # UI Enhancements
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  flutter_spinkit: ^5.2.1
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^3.1.1
  
  # Form & Validation
  form_field_validator: ^1.1.0
  email_validator: ^2.1.17
  
  # Payment (for future implementation)
  # stripe_payment: ^1.1.4
  
  # Permissions
  permission_handler: ^11.3.1
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/uploads/

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
