// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf4kIbG0uCmcSVpvC6qVU1umppbmVapbs',
    appId: '1:290254260284:web:71f25fa7b437900620db39',
    messagingSenderId: '290254260284',
    projectId: 'eggstra-farms-ltd',
    authDomain: 'eggstra-farms-ltd.firebaseapp.com',
    databaseURL: 'https://eggstra-farms-ltd-default-rtdb.firebaseio.com',
    storageBucket: 'eggstra-farms-ltd.firebasestorage.app',
    measurementId: 'G-LCC1D6TFJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwK8hax-bRJIhMkCHoa3D1Gf3Ax4XJY_0',
    appId: '1:290254260284:android:3b33cec024fe99cc20db39',
    messagingSenderId: '290254260284',
    projectId: 'eggstra-farms-ltd',
    databaseURL: 'https://eggstra-farms-ltd-default-rtdb.firebaseio.com',
    storageBucket: 'eggstra-farms-ltd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzOblNJOtI4GQlKuLyBIP8e_v-it2djtk',
    appId: '1:290254260284:ios:859f63b071ea939e20db39',
    messagingSenderId: '290254260284',
    projectId: 'eggstra-farms-ltd',
    databaseURL: 'https://eggstra-farms-ltd-default-rtdb.firebaseio.com',
    storageBucket: 'eggstra-farms-ltd.firebasestorage.app',
    iosBundleId: 'com.eggstrafarmsghana.eggstraFarmsLtd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzOblNJOtI4GQlKuLyBIP8e_v-it2djtk',
    appId: '1:290254260284:ios:859f63b071ea939e20db39',
    messagingSenderId: '290254260284',
    projectId: 'eggstra-farms-ltd',
    databaseURL: 'https://eggstra-farms-ltd-default-rtdb.firebaseio.com',
    storageBucket: 'eggstra-farms-ltd.firebasestorage.app',
    iosBundleId: 'com.eggstrafarmsghana.eggstraFarmsLtd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf4kIbG0uCmcSVpvC6qVU1umppbmVapbs',
    appId: '1:290254260284:web:d6cd1823a9fb30bb20db39',
    messagingSenderId: '290254260284',
    projectId: 'eggstra-farms-ltd',
    authDomain: 'eggstra-farms-ltd.firebaseapp.com',
    databaseURL: 'https://eggstra-farms-ltd-default-rtdb.firebaseio.com',
    storageBucket: 'eggstra-farms-ltd.firebasestorage.app',
    measurementId: 'G-8K35768FV5',
  );

}